version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"   # Mapeamento da porta 8090 interna para a porta 9090 na máquina local
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ./target:/app/target
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/plataforma_medicos?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=conexa123
      - JWT_SECRET=my-secret-key
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: conexa123
      MYSQL_DATABASE: plataforma_medicos
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: